# font pango:JetBrainsMono Nerd Font Mono 13
# font pango:UbuntuMono Nerd Font Mono 13
font pango:Hack Nerd Font Mono 13

# Use mouse+$mod to drag floating windows
floating_modifier $mod

# Add gaps
gaps inner 10
gaps outer 10

# Set border width
default_border pixel 4
default_floating_border pixel 4
