exec_always --no-startup-id picom --config $HOME/.config/picom/picom.conf
exec_always --no-startup-id dunst
exec_always --no-startup-id $HOME/.config/polybar/launch.sh
exec_always --no-startup-id feh --bg-center --bg-scale ~/.config/backgrounds/wallpaper-ubuntu.png

exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id nm-applet
