client.focused          $accent $accent $fg $accent $accent
client.focused_inactive $bg-alt $bg-alt $fg $bg-soft $bg-soft
client.unfocused        $bg-alt $bg-alt $fg $bg-soft $bg-soft
client.urgent           $err $err $bg $err $err
