# Define names for default workspaces
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# Set monitor names
set $monitor_center "DP-2"
set $monitor_right "HDMI-0"
set $monitor_left "DP-0"

# Assign workspaces to specific monitors
workspace $ws1 output $monitor_center
workspace $ws3 output $monitor_right
workspace $ws4 output $monitor_left
