set $bg           #24273a
set $bg-alt       #363a4f
set $bg-soft      #494d64
set $fg           #cad3f5
set $accent       #8aadf4
set $err          #ed8796
set $focused_text #24273a
set $urgent_text  #24273a
