set $bg           #191724
set $bg-alt       #1f1d2e
set $bg-soft      #26233a
set $fg           #e0def4
set $accent       #c4a7e7
set $err          #eb6f92
set $focused_text #191724
set $urgent_text  #191724
